name: Ruby Gem

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.5
    
    - name: Install Dependencies
      run: |
        gem install bundler
    
    - name: Install gems
      run: |
        bundle install
    
    - name: Run tests
      run: |
        bundle exec rspec
